### ISSUE TITLE
dictionary does not find "Agorithmus"

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#11]
`notes.tex` eventually includes `/Users/kohlhase/localmh/MathHub/MiKoMH/GenICT/source/programming/en/program-execution.tex`, which has 
```LaTeX
    \begin{definition}[display=flow,id=algorithm.def]
      \Defi{algorithm}: informal description of what to do (good enough for
      humans)
    \end{definition}
```
and indeed, there is an english entry for `algorithm`, but none for `Algorithmus`, even though `smglom/IWGS/source/algorithm.de.tex` exists and has 
```LaTeX
 Ein \defi[name=algorithm]{Algorithmus} ist eine formale oder informelle Spezifikation
```

**Comment by jfschaefer** [comment]
That probably happens, because the dictionary generator does not associate that definition of `algorithm` in `program-execution.tex` with the definition in `smglom/IWGS`.

Isn't the definition in `program-execution.tex` rather a `Drefi` than a `Defi`? Then it would be linked to the entry in `smglom/IWGS`.
